name: Run tests

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          # - '~1.8.0-rc1'
          - '1'
          - 'nightly'
        nthreads:
          - '1'
          - '2'
          - '4'
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }} nthreads=${{ matrix.nthreads }}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: ${{ matrix.nthreads }}
          TEST_FUNCTION_RUNNER_JL_TIMEOUT: "1200"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella

  aqua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          - '1'
          - 'nightly'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path = "."))
          Pkg.add([
              PackageSpec(name = "Aqua", version = "0.5"),
          ])
        shell: julia --color=yes {0}
      - name: Run Aqua
        run: |
          using Aqua
          using ConcurrentUtils
          Aqua.test_all(ConcurrentUtils; unbound_args = false)
        shell: julia --color=yes {0}

  # A job that succeeds if and only if all jobs in `test` succeed.
  all-success:
    if: always() && github.event.pull_request
    needs: [test, aqua]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/tkf/merge-conclusions-action
      - uses: tkf/merge-conclusions-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
